neptune-ai/examples

integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch_Support.ipynb
Noticed some bugs with the notebook when I run it. 
Here is the fix!
=> :bug: Fixing minor bugs [notebook]

integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py, integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch_Support.ipynb, integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch_Support.py, integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch_Support_more_options.py, integrations-and-supported-tools/pytorch/scripts/requirements.txt
Reverts neptune-ai/examples#36
=> Revert ":ambulance: Unfreeze neptune version"

how-to-guides/hello-world/notebooks/Neptune_hello_world.ipynb, how-to-guides/how-it-works/notebooks/Neptune_API_Tour.ipynb, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb, integrations-and-supported-tools/colab/Neptune_Colab.ipynb, integrations-and-supported-tools/sklearn/notebooks/Neptune_Scikit_learn.ipynb, integrations-and-supported-tools/tensorflow-keras/notebooks/Neptune_TensorFlow_Keras.ipynb, product-tours/how-it-works/docs/Neptune-API-Tour.ipynb, quick-starts/first-run/docs/Use-Neptune-API-to-log-your-first-run.ipynb
* we had project_qualified_name in the notes (not in code) -> fixed it
=> fixed initialization notes

how-to-guides/create-delete-projects/notebooks/Create_delete_projects.ipynb
Removed `[:10]` from `management.delete_project(name="common/YOUR_PROJECT", api_token="YOUR_API_TOKEN")[:10]`
__Related to:__ `(ClickUp/JIRA task link)`
---
---
Share the link of the documentation branch with changes: `(link)`
---
- OS:
---
These tasks should be done after the code is merged to main. Please create a subtask under the main ClickUp task to have these on your radar and share the subtask here.
__Post-merge subtask:__ `(ClickUp/JIRA task link)`
=> Fixed error in Create_delete_projects.ipynb

.github/workflows/branch.yml
Added timeout for `pull_request` tests
__Related to:__ `(ClickUp/JIRA task link)`
---
---
Share the link of the documentation branch with changes: `(link)`
---
- OS:
---
These tasks should be done after the code is merged to main. Please create a subtask under the main ClickUp task to have these on your radar and share the subtask here.
__Post-merge subtask:__ `(ClickUp/JIRA task link)`
=> Added timeout for PR tests

.github/workflows/pull-request.yml, .github/workflows/schedules-macos.yml, .github/workflows/schedules-ubuntu.yml, .github/workflows/schedules-windows.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml, .pre-commit-config.yaml
Syncing pre-commit configuration with that used in `neptune-client`
__Related to:__ [Standardize pre-commit checks](https://app.clickup.com/t/3884pg1)
---
---
Share the link of the documentation branch with changes: `(link)`
---
- OS: Windows 11
---
These tasks should be done after the code is merged to main. Please create a subtask under the main ClickUp task to have these on your radar and share the subtask here.
__Post-merge subtask:__ `(ClickUp/JIRA task link)`
=> Syncing pre-commit with Neptune client

.github/pull_request_template.md, how-to-guides/how-it-works/notebooks/Neptune_API_Tour.ipynb, how-to-guides/how-it-works/scripts/Neptune_API_Tour_more_logging_options.py, integrations-and-supported-tools/altair/notebooks/Neptune_Altair_Support.ipynb, integrations-and-supported-tools/altair/scripts/Neptune_Altair_Support.py, integrations-and-supported-tools/bokeh/notebooks/Neptune_Bokeh_Support.ipynb, integrations-and-supported-tools/bokeh/scripts/Neptune_Bokeh_Support.py, integrations-and-supported-tools/html/notebooks/Neptune_HTML_Support.ipynb, integrations-and-supported-tools/html/notebooks/sample.html, integrations-and-supported-tools/html/scripts/Neptune_HTML_Support.py, integrations-and-supported-tools/matplotlib/notebooks/Neptune_Matplotlib_Support.ipynb, integrations-and-supported-tools/matplotlib/scripts/Neptune_Matplotlib_Support.py, integrations-and-supported-tools/plotly/notebooks/Neptune_Plotly_Support.ipynb, integrations-and-supported-tools/plotly/scripts/Neptune_Plotly_Support.py, integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, integrations-and-supported-tools/pytorch-lightning/scripts/Neptune_Pytorch_Lightning_more_options.py, integrations-and-supported-tools/tensorflow-keras/notebooks/Neptune_TensorFlow_Keras.ipynb, integrations-and-supported-tools/tensorflow-keras/scripts/Neptune_TensorFlow_Keras_more_options.py, sample.html
* Removing explicit casting from `log()` and `upload()` where not required
* Importing `File` from `neptune.new.types` where type casting explicitly required
* Formatting impacted notebooks/scripts
__Related to:__ [Import types in example scripts](https://app.clickup.com/t/2p89rx5)
---
---
Share the link of the documentation branch with changes: `(link)`
---
- OS: Windows 11
- Python version: `3.10.5`
- Neptune version: `0.16.4`
- Affected libraries with version: NA
---
These tasks should be done after the code is merged to main. Please create a subtask under the main ClickUp task to have these on your radar and share the subtask here.
__Post-merge subtask:__ `(ClickUp/JIRA task link)`
=> Importing `File` from `neptune.new.types`

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
* Increased timeout to 15 mins
* Added docker script test to `test-scripts.yml`
* Updated `checkout` to v3 and `setup-python` to v4
---
---
---
- OS:
---
=> Updated github actions

.pre-commit-config.yaml
Ref: https://github.com/PyCQA/isort/issues/1518
=> update precommit-hook for isort and black conflict

integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, integrations-and-supported-tools/pytorch-lightning/scripts/requirements.txt
Temporarily fixes the dependencies of the PyTorch Lightning notebook example, until Lightning AI releases the pending changes to `NeptuneLogger`.
This workaround can be reverted once the relevant PTL version is released.
__Related to:__ `NPT-12380`
---
---
---
- OS:
---
=> Temporary PTL workaround, per NPT-12380

.github/workflows/test-scripts.yml
Removing `test-docker-example` from `test-scripts.yml` as it is already being run in `schedules-ubuntu.yml`
---
---
---
- OS:
---
=> Removed test-docker-example from test-scripts.yml

integrations-and-supported-tools/fastai/scripts/Neptune_fastai.py, integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py, integrations-and-supported-tools/fastai/scripts/run_examples.sh, integrations-and-supported-tools/pytorch-lightning/scripts/Neptune_Pytorch_Lightning_more_options.py, integrations-and-supported-tools/pytorch-lightning/scripts/run_examples.sh
Fixing test errors
---
---
---
- OS: `Windows 11`
- Python version: `3.10.5`
- Neptune version: `0.16.9`
- Affected libraries with version: `fastai==2.6.3 neptune-fastai==0.10.3 pytorch-lightning==1.6.4`
---
=> Fixing fastai and ptl errors

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
Updated `actions/cache` from `v2` to `v3.0.11`
---
---
---
- OS:
---
=> Updated gh actions/cache to v3.0.11

.github/workflows/pull-request.yml
Added separate section for Kedro is PR tests
__Related to:__ `Fix kedro PR tests`
---
---
---
- OS:
---
=> Added separate tests for kedro

how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb
Fixes #134 
---
---
---
- OS:
---
=> Fix for hanging runs

.github/workflows/pull-request.yml, .github/workflows/schedules-macos-notebooks.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
* Replacing pip cache actions with inbuilt caching of `setup-python`
* Pinning only base versions of external actions
---
---
---
- OS:
---
=> Pinning only base versions of actions

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
* Added python v3.11 to test matrix
* Added step-level timeout
__Related to:__ `Add tests for py3.11`
---
---
---
- OS:
---
=> Added python v3.11 to test matrix

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
Using `nick-fields/retry@v2` to retry timed-out steps.
Some actions timeout on their first try due to runner throttling, and run fine if re-run. This step will automate the rerun only for timed-out steps.
---
---
---
- OS:
---
=> Added retry_on timeout

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
Changed working directory to handle script tests
---
---
---
- OS:
---
=> Fixed test-scripts step

integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb, integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_customize_callback.py, integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_load_study.py, integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_log_after_study.py, integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_log_study_and_trial_level.py, integrations-and-supported-tools/optuna/scripts/Neptune_Optuna_integration_quickstart.py
Updated optuna examples with new API
__Related to:__ `Update examples to use the new API`
---
---
---
- OS:
---
=> Updated Optuna example with new API

how-to-guides/data-versioning/notebooks/Compare_model_training_runs_on_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Organize_and_share_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Version_datasets_in_model_training_runs.ipynb, how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/how-it-works/notebooks/Neptune_API_Tour.ipynb, how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb, how-to-guides/present-cross-validation-results/notebooks/Neptune_cross_validation.ipynb, integrations-and-supported-tools/altair/notebooks/Neptune_Altair_Support.ipynb, integrations-and-supported-tools/bokeh/notebooks/Neptune_Bokeh_Support.ipynb, integrations-and-supported-tools/catalyst/notebooks/Neptune_Catalyst.ipynb, integrations-and-supported-tools/colab/Neptune_Colab.ipynb, integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/html/notebooks/Neptune_HTML_Support.ipynb, integrations-and-supported-tools/lightgbm/notebooks/Neptune_LightGBM.ipynb, integrations-and-supported-tools/matplotlib/notebooks/Neptune_Matplotlib_Support.ipynb, integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb, integrations-and-supported-tools/plotly/notebooks/Neptune_Plotly_Support.ipynb, integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch_Support.ipynb, integrations-and-supported-tools/sacred/notebooks/Neptune_Sacred.ipynb, integrations-and-supported-tools/sklearn/notebooks/Neptune_Scikit_learn.ipynb, integrations-and-supported-tools/tensorflow-keras/notebooks/Neptune_TensorFlow_Keras.ipynb, integrations-and-supported-tools/transformers/notebooks/Neptune_Transformers.ipynb, integrations-and-supported-tools/xgboost/notebooks/Neptune_XGBoost.ipynb, product-tours/how-it-works/docs/Neptune-API-Tour.ipynb, quick-starts/first-run/docs/Use-Neptune-API-to-log-your-first-run.ipynb
* Replaced "ANONYMOUS" with `neptune.ANONYMOUS_API_TOKEN` in notebooks
* Formatted with isort and black
* Replaced single quotes `'` with double-quoted `"` in comments
__Related to:__ `Update examples to use the new API`
---
---
---
- OS:
---
=> Updated notebooks

.pre-commit-config.yaml
As per the title (other repos, will need the same changes)
=> update pre-commit to run black on jupyter notebook

README.md
=> Update README with DDP tutorial link

how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb, how-to-guides/neptune-hpo/scripts/Neptune_hpo_separate_runs.py, how-to-guides/neptune-hpo/scripts/requirements.txt
=> remove unused dependency

how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, integrations-and-supported-tools/catalyst/notebooks/Neptune_Catalyst.ipynb, integrations-and-supported-tools/catalyst/scripts/requirements.txt, integrations-and-supported-tools/catalyst/scripts/run_examples.sh, integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/fastai/scripts/requirements.txt, integrations-and-supported-tools/fastai/scripts/run_examples.sh, integrations-and-supported-tools/kedro/scripts/kedro_neptune_advanced/src/requirements.txt, integrations-and-supported-tools/kedro/scripts/kedro_neptune_advanced/src/setup.py, integrations-and-supported-tools/kedro/scripts/kedro_neptune_quickstart/src/requirements.txt, integrations-and-supported-tools/kedro/scripts/requirements.txt, integrations-and-supported-tools/kedro/scripts/run_examples.sh, integrations-and-supported-tools/lightgbm/notebooks/Neptune_LightGBM.ipynb, integrations-and-supported-tools/lightgbm/scripts/requirements.txt, integrations-and-supported-tools/lightgbm/scripts/run_examples.sh, integrations-and-supported-tools/matplotlib/notebooks/Neptune_Matplotlib_Support.ipynb, integrations-and-supported-tools/matplotlib/scripts/requirements.txt, integrations-and-supported-tools/matplotlib/scripts/run_examples.sh, integrations-and-supported-tools/plotly/notebooks/Neptune_Plotly_Support.ipynb, integrations-and-supported-tools/plotly/scripts/requirements.txt, integrations-and-supported-tools/plotly/scripts/run_examples.sh, integrations-and-supported-tools/prophet/scripts/requirements.txt, integrations-and-supported-tools/prophet/scripts/run_examples.sh, integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch_Support.ipynb, integrations-and-supported-tools/tensorflow/scripts/run_examples.sh
* Unpinned dependencies,
* Added `-U` and removed `-q` flags from pip install
* Added `-e` flag to run_examples.sh
__Note:__
* Kedro tests failing due to project and dependency version mismatch. Will be fixed in an upcoming patch
---
---
---
- OS:
=> Fixed pip install - II

how-to-guides/create-delete-projects/scripts/run_examples.sh, how-to-guides/hello-neptune/scripts/run_examples.sh, integrations-and-supported-tools/html/scripts/run_examples.sh, integrations-and-supported-tools/kedro/scripts/kedro_neptune_quickstart/src/setup.py, integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, integrations-and-supported-tools/pytorch-lightning/scripts/requirements.txt, integrations-and-supported-tools/pytorch-lightning/scripts/run_examples.sh, integrations-and-supported-tools/pytorch/scripts/requirements.txt, integrations-and-supported-tools/pytorch/scripts/run_examples.sh, integrations-and-supported-tools/sacred/notebooks/Neptune_Sacred.ipynb, integrations-and-supported-tools/sklearn/notebooks/Neptune_Scikit_learn.ipynb, integrations-and-supported-tools/sklearn/scripts/requirements.txt, integrations-and-supported-tools/sklearn/scripts/run_examples.sh, integrations-and-supported-tools/skorch/notebooks/Neptune_Skorch.ipynb, integrations-and-supported-tools/skorch/scripts/requirements.txt, integrations-and-supported-tools/skorch/scripts/run_examples.sh, integrations-and-supported-tools/transformers/notebooks/Neptune_Transformers.ipynb, integrations-and-supported-tools/transformers/scripts/requirements.txt, integrations-and-supported-tools/transformers/scripts/run_examples.sh, integrations-and-supported-tools/xgboost/notebooks/Neptune_XGBoost.ipynb, integrations-and-supported-tools/xgboost/scripts/requirements.txt, integrations-and-supported-tools/xgboost/scripts/run_examples.sh
* Unpinned dependencies
* Added `-U` and removed `-q` flags from pip install
* Tests on python3.11 might fail due to version incompatibilities
---
---
---
- OS:
=> Fixed pip install - III

README.md
Link from the SageMaker section to the AWS Secrets tutorial in the docs.
---
=> Add docs link to SageMaker section

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb
* Removed screenshots
* Updated structure
* Tests on python 3.11 will fail
---
---
---
- OS:
=> Removed screenshots

integrations-and-supported-tools/sacred/notebooks/Neptune_Sacred.ipynb
Let's set also this to `neptune_run` so it matches the rest of the example.
---
---
---
- OS:
=> Fix run variable

integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch_Support.ipynb, integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch_Support.py, integrations-and-supported-tools/pytorch/scripts/Neptune_Pytorch_Support_more_options.py
Fixing pytorch test error
Tests on python 3.11 will fail due to version incompatibility
---
---
---
- OS: Windows
- Neptune version: 0.16.16
=> Fixing pytorch error

integrations-and-supported-tools/xgboost/scripts/Neptune_XGBoost_sklearn_api.py
Fixed xgboost example test error
---
---
---
- Neptune version: 0.16.17
=> Fixed xgboost error

how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb, how-to-guides/neptune-hpo/scripts/Neptune_hpo_separate_runs.py, how-to-guides/neptune-hpo/scripts/Neptune_hpo_single_run.py, how-to-guides/present-cross-validation-results/notebooks/Neptune_cross_validation.ipynb, how-to-guides/present-cross-validation-results/scripts/neptune_cross_validation.py
Replaced `math.prod()` with `functools.reduce()`
Tests will fail on python3.11
---
---
---
- Python version: 3.7.12
- Neptune version: 0.16.17
=> Fix for python3.7

integrations-and-supported-tools/kedro/scripts/run_examples.sh
Updated kedro test setup
Tests on python3.11 will fail
---
---
---
- OS:
=> Fixing kedro test error

.github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
Updated tests to exclude detectron2 from running on windows
---
---
---
- OS:
=> Updated tests to exclude detectron2 on windows

use-cases/time-series-forecasting/walmart-sales/requirements.txt, use-cases/time-series-forecasting/walmart-sales/scripts/run_dl_lstm.py, use-cases/time-series-forecasting/walmart-sales/scripts/run_dl_lstm_finetune.py, use-cases/time-series-forecasting/walmart-sales/scripts/run_ml_prophet.py
* Added model registry to prophet code
* Removed neptune-client from LSTM
* Tests might fail on python3.11
* Project used neptune>1.0.0 which s not supported by our PTL integration yet
---
---
---
- Neptune version: 1.1.1
- Affected libraries with version: neptune-prophet==1.0.0
=> Updated TSF project

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/hello-neptune/scripts/hello_neptune.py, how-to-guides/hello-neptune/scripts/requirements.txt, how-to-guides/hello-neptune/scripts/run_examples.sh
Updated quickstart notebook and script
* Add dependency tracking once the latest `neptune` client is released
* Add showcase run
* Update README.md
__Related to:__ `Update quickstart example`
Notebooks will fail tests due to the `input()` method
---
---
---
- Neptune version: 1.2.0
=> Updated quickstart

.sourcery.yaml, how-to-guides/sequential-pipelines/scripts/model_promotion.py, how-to-guides/sequential-pipelines/scripts/requirements.txt, how-to-guides/sequential-pipelines/scripts/run_examples.sh
Constraining simplejson to <3.19 
---
---
---
- Neptune version: 1.2.2
- Affected libraries with version: simplejson==3.8.14
=> Constraining simplejson

integrations-and-supported-tools/keras/notebooks/Neptune_Keras.ipynb, integrations-and-supported-tools/keras/scripts/requirements.txt
Fixed pip install
---
---
---
- OS:
=> Fixed neptune-tensorflow-keras installation

integrations-and-supported-tools/sklearn/notebooks/Neptune_Scikit_learn.ipynb, integrations-and-supported-tools/sklearn/scripts/Neptune_Scikit_learn_classification.py, integrations-and-supported-tools/sklearn/scripts/Neptune_Scikit_learn_other_options.py, integrations-and-supported-tools/sklearn/scripts/Neptune_Scikit_learn_regression.py, integrations-and-supported-tools/sklearn/scripts/requirements.txt
* `! pip install neptune-sklearn` > `%pip install neptune[sklearn]`
* Updated model params in notebook
---
---
---
- Neptune version: 1.3.1
- Affected libraries with version: scikit-learn==1.2.2
=> Fixed pip install and updated params

integrations-and-supported-tools/transformers/notebooks/Neptune_Transformers.ipynb, integrations-and-supported-tools/transformers/scripts/requirements.txt
Added `pip install transformers[torch]`
---
---
---
- Neptune version: 1.3.1
- Affected libraries with version: transformers==4.30.2
=> Updated pip install

integrations-and-supported-tools/transformers/notebooks/Neptune_Transformers.ipynb, integrations-and-supported-tools/transformers/scripts/requirements.txt, integrations-and-supported-tools/transformers/scripts/run_examples.sh
Testing optimal pip install setup
---
---
---
- Neptune version: 1.3.1
- Affected libraries with version: scikit-learn==1.2.2
=> Testing pip install

integrations-and-supported-tools/xgboost/notebooks/Neptune_XGBoost.ipynb, integrations-and-supported-tools/xgboost/scripts/Neptune_XGBoost_cv.py, integrations-and-supported-tools/xgboost/scripts/Neptune_XGBoost_sklearn_api.py, integrations-and-supported-tools/xgboost/scripts/Neptune_XGBoost_train.py, integrations-and-supported-tools/xgboost/scripts/requirements.txt
Fixed pip install
---
---
---
- OS:
=> Fixed pip install

use-cases/nlp/classification/keras/code/keras_nb.ipynb, use-cases/nlp/classification/keras/code/keras_script.py, use-cases/nlp/classification/keras/code/requirements.txt
Updated pip install
---
---
---
- OS:
=> Update Text classification using keras project

.github/workflows/pull-request.yml, README.md, utils/migration_tools/from_another_project/README.md, utils/migration_tools/from_another_project/runs_migrator.py
Initial version of script used to migrate runs from one project to another
__Related to:__ Project run migrator
---
---
---
- Neptune version: 1.3.1
=> Runs migration script

integrations-and-supported-tools/tensorboard/notebooks/Neptune_Tensorflow_Tensorboard.ipynb, integrations-and-supported-tools/tensorboard/scripts/requirements.txt
Added `tensorboard` optional dependency
__Related to:__ Tensorboard example
---
---
---
- OS:
=> Updated tensorboard installation

integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, integrations-and-supported-tools/pytorch-lightning/scripts/Neptune_Pytorch_Lightning.py, integrations-and-supported-tools/pytorch-lightning/scripts/Neptune_Pytorch_Lightning_more_options.py, integrations-and-supported-tools/pytorch-lightning/scripts/requirements.txt
* Updated pydantic
* Updated imports
---
---
---
- Neptune version: 1.4.1
- Affected libraries with version: lightning==2.0.6
=> Updated PTL example

integrations-and-supported-tools/dalex/notebooks/Neptune_Dalex.ipynb
Fixed Dalex example
---
---
---
- Neptune version: 1.5.0
- Affected libraries with version: dalex==1.6.0
=> Fixed dalex notebook

use-cases/nlp/classification/keras/code/keras_nb.ipynb, use-cases/nlp/classification/keras/code/keras_script.py
Trying `wait() instead of `sync()`
---
---
---
- OS:
=> Using `wait()` instead of `sync()`

integrations-and-supported-tools/skorch/notebooks/Neptune_Skorch.ipynb, integrations-and-supported-tools/skorch/scripts/requirements.txt
Installed matplotlib
---
---
---
- Neptune version: 1.5.0
- Affected libraries with version: 0.14.0
=> Fix skorch example

integrations-and-supported-tools/pandas/notebooks/Neptune_Pandas.ipynb
Added `--user` flag to pip install
---
---
---
- OS:
=> Added `--user` flag

.github/workflows/test-scripts.yml, README.md, integrations-and-supported-tools/airflow/scripts/Neptune_Airflow.py, integrations-and-supported-tools/airflow/scripts/requirements.txt, integrations-and-supported-tools/airflow/scripts/run_examples.sh
__Related to:__ <ClickUp/JIRA task name>
---
---
---
- OS: Ubuntu
- Python version: 3.10
- Neptune version: 1.4.1
- Affected libraries with version: Airflow 2.6.3 , Tensorflow 2.13.0
=> airflow example

integrations-and-supported-tools/altair/notebooks/Neptune_Altair_Support.ipynb, integrations-and-supported-tools/altair/scripts/Neptune_Altair_Support.py, integrations-and-supported-tools/altair/scripts/run_examples.sh
* `.selection()` -> `.selection_interval()`
* `.add_selection()` -> `.add_params()`
---
---
---
- Neptune version: 1.8.2
- Affected libraries with version: altair==5.1.2
=> Update deprecated methods

integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/prophet/scripts/Neptune_prophet.py, integrations-and-supported-tools/prophet/scripts/Neptune_prophet_more_options.py, integrations-and-supported-tools/prophet/scripts/requirements.txt, use-cases/time-series-forecasting/walmart-sales/requirements.txt
Simplifying requirements for prophet examples
---
---
---
- Neptune version: 1.8.2
- Affected libraries with version: neptune-prophet==1.0.0.post2+cde9b54
=> Simplifying requirements

.github/workflows/adhoc-test.yml, .github/workflows/pull-request.yml, .github/workflows/test-scripts.yml, integrations-and-supported-tools/detectron2/scripts/requirements.txt, integrations-and-supported-tools/detectron2/scripts/run_examples.sh
Updated build for detectron2 example
---
---
---
- OS:
=> Updated build process

use-cases/time-series-forecasting/walmart-sales/scripts/run_dl_lstm_finetune.py
Calling `load_from_checkpoint()` from class type instead of instance
---
---
---
- Neptune version: 1.8.6
- Affected libraries with version: lightning==2.1.3
=> Fixed TSF `load_from_checkpoint()`

integrations-and-supported-tools/azure-ml/components/data_prep/data_preprocessing.py, integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb, use-cases/nlp/summarization/hf_transformers/scripts/run_summarization.py
- Fix sample code for supplying your own credentials
- Standardize language
- Update UI instructions
__Related to:__
---
---
---
- OS:
=> tweak language and fix sample code

.github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml, how-to-guides/sequential-pipelines/scripts/model_validation.py
__Related to:__ <ClickUp/JIRA task name>
---
---
---
- OS:
=> Fixes for tests

integrations-and-supported-tools/detectron2/scripts/run_examples.sh
Fix detectron2 installation issues on MacOS
---
---
---
- OS:
=> Fix detectron2 installation issues on MacOS

how-to-guides/sequential-pipelines/scripts/requirements.txt
Removed simplejson from sequential pipelines requirements
---
---
---
- Neptune version: 1.9.1
=> Removed simplejson from requirements

integrations-and-supported-tools/kedro/scripts/requirements.txt
Added kedro optional dependency to neptune install
---
---
---
- OS:
=> Added kedro optional dependency to neptune install

README.md, utils/management_tools/Get_runs_with_most_fields.ipynb, utils/management_tools/Get_storage_used_by_project_user.ipynb
* Added notebook to show runs with the most fields logged
* Updated `utils` folder structure
__Related to:__ <ClickUp/JIRA task name>
---
---
---
- OS:
=> Added new utility notebook

how-to-guides/multiple-integrations/notebooks/Multiple_integrations.ipynb
Using aggreated backend for matplotlib to prevent `Tcl_AsyncDelete` error
---
---
---
- OS:
=> Using aggregated backend

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/hello-neptune/notebooks/requirements.txt, how-to-guides/hello-neptune/scripts/hello_neptune.py, how-to-guides/hello-neptune/scripts/requirements.txt
Updated the info on finding project name in the Neptune app plus some minor fixes. 
__Related to:__ ClickUp 86940tqya
---
---
---
- OS:
=> Review and update the Hello Neptune notebook

how-to-guides/create-delete-projects/notebooks/Create_delete_projects.ipynb, how-to-guides/data-versioning/notebooks/Compare_model_training_runs_on_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Organize_and_share_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Version_datasets_in_model_training_runs.ipynb, how-to-guides/e2e-tracking/notebooks/e2e_tracking.ipynb, how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, how-to-guides/multiple-integrations/notebooks/Multiple_integrations.ipynb, how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb, integrations-and-supported-tools/catalyst/notebooks/Neptune_Catalyst.ipynb, integrations-and-supported-tools/colab/Neptune_Colab.ipynb, integrations-and-supported-tools/detectron2/notebooks/Neptune_detectron2.ipynb, integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/html/notebooks/Neptune_HTML_Support.ipynb, integrations-and-supported-tools/keras/notebooks/Neptune_Keras.ipynb, integrations-and-supported-tools/sacred/notebooks/Neptune_Sacred.ipynb, integrations-and-supported-tools/sklearn/notebooks/Neptune_Scikit_learn.ipynb, integrations-and-supported-tools/skorch/notebooks/Neptune_Skorch.ipynb, integrations-and-supported-tools/tensorboard/notebooks/Neptune_Tensorflow_Tensorboard.ipynb, integrations-and-supported-tools/xgboost/notebooks/Neptune_XGBoost.ipynb
Fixed pip install in notebooks
---
---
---
- OS:
=> chore: Updated pip install

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb, how-to-guides/restart-run-from-checkpoint/notebooks/neptune_save_restart_run_from_checkpoint.ipynb, how-to-guides/restart-run-from-checkpoint/scripts/requirements.txt, how-to-guides/restart-run-from-checkpoint/scripts/run_examples.sh, integrations-and-supported-tools/mosaicml-composer/notebooks/Neptune_MosaicML_Composer.ipynb, integrations-and-supported-tools/mosaicml-composer/scripts/requirements.txt, integrations-and-supported-tools/mosaicml-composer/scripts/run_examples.sh, integrations-and-supported-tools/pytorch-ignite/notebooks/Neptune_PyTorch_Ignite.ipynb, integrations-and-supported-tools/pytorch-ignite/scripts/requirements.txt, integrations-and-supported-tools/pytorch-ignite/scripts/run_examples.sh, integrations-and-supported-tools/pytorch/notebooks/Neptune_PyTorch.ipynb, integrations-and-supported-tools/pytorch/scripts/requirements.txt, integrations-and-supported-tools/pytorch/scripts/run_examples.sh, integrations-and-supported-tools/skorch/notebooks/Neptune_Skorch.ipynb, integrations-and-supported-tools/skorch/scripts/requirements.txt, integrations-and-supported-tools/skorch/scripts/run_examples.sh
=> chore: Pinned numpy to <2.0

integrations-and-supported-tools/transformers/notebooks/Neptune_Transformers.ipynb, integrations-and-supported-tools/transformers/scripts/Neptune_Transformers.py, integrations-and-supported-tools/transformers/scripts/Neptune_Transformers_report_to.py, integrations-and-supported-tools/transformers/scripts/requirements.txt, integrations-and-supported-tools/transformers/scripts/run_examples.sh
* Set `save_safetensors=False` to prevent error while saving tensors
* Added additional depenedencies
* Updated training args across runs
---
---
---
- Neptune version: 1.10.4
- Affected libraries with version: transformers==4.43.3
=> fix: Fixed transformers example

utils/migration_tools/from_wandb/README.md, utils/migration_tools/from_wandb/wandb_to_neptune.py, utils/migration_tools/model_registry_to_runs/README.md, utils/migration_tools/model_registry_to_runs/model_to_run.py
* Improved performance by >6x
* Improved README with benchmark and post-migration information
__Related to:__ Improve W&B migration script
---
---
---
- OS:
- Neptune version: 1.10.4
- Affected libraries with version: wandb==0.17.4
=> Improved W&B migration script

.github/CONTRIBUTING.md, README.md, community-code/README.md
Added community-code folder to house blog code
__Related to:__ Community code folder in examples repo
---
---
---
- OS:
=> feat: Added community code folder

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/hello-neptune/scripts/hello_neptune.py, how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, how-to-guides/monitor-ml-runs/scripts/Monitor_ML_runs_live.py, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb, how-to-guides/organize-ml-experimentation/scripts/Organize_ML_runs.py
Temporarily divert quickstarts to the `showcase` workspace.
---
---
---
- OS:
=> Divert quickstarts to o/showcase

README.md
1. Pull in banner from main client assets
1. Update the messaging
__Related to:__ -
__Any expected test failures?__ -
---
---
---
- OS:
=> Update banner and messaging in README

README.md, utils/migration_tools/backup_neptune/README.md, utils/migration_tools/from_wandb/README.md
__Related to:__ <ClickUp/JIRA task name>
---
---
---
- OS:
=> chore: Replace `legacy` with `2.x`
