integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/fastai/scripts/requirements.txt
Our tutorial example for fastai was failing with the error `RuntimeError: Could not infer dtype of PILImage`. It seems like it's a [bug in fastai](https://forums.fast.ai/t/runtimeerror-could-not-infer-dtype-of-pilimage/89697/5). I bumped the version to the most recent and it works again.
=> Bump fastai version to most recent

.github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml
Replaced deprecated `set-output` command with github env variables. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
---
---
---
- OS:
---
=> Removed deprecated `set-output` in scheduled tests

.github/pull_request_template.md
I think we can make do with one "update docs" item which can be checked as soon as the changes are understood and taken into account. That is, for new content, the new docs page does not need to be published before a PR can be merged.
If the docs content is added later (which I think will more often be the case now that we have a separate docs team), I'll take over the responsibility to add links and update the examples README once the content is published.
What do you think?
=> Adjust docs items in PR template

README.md
Add docs link to "Re-run failed training" examples.
__Related to:__ `Tutorial: Re-running failed training`
=> Add docs link for "Re-run failed training"

.github/workflows/pull-request.yml, .github/workflows/test-scripts.yml
* Added ddp code to scheduled tests
* Ignoring ddp code in PR tests
__Related to:__ `DDP training examples`
---
---
---
- OS:
=> Handling ddp training tests

how-to-guides/data-versioning/notebooks/Compare_model_training_runs_on_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Organize_and_share_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Version_datasets_in_model_training_runs.ipynb, how-to-guides/data-versioning/scripts/requirements.txt, how-to-guides/data-versioning/scripts/run_examples.sh, how-to-guides/ddp-training/scripts/requirements.txt, how-to-guides/ddp-training/scripts/run_examples.sh, how-to-guides/how-it-works/notebooks/Neptune_API_Tour.ipynb, how-to-guides/how-it-works/scripts/requirements.txt, how-to-guides/how-it-works/scripts/run_examples.sh, how-to-guides/monitor-ml-runs/scripts/requirements.txt, how-to-guides/monitor-ml-runs/scripts/run_examples.sh, how-to-guides/neptune-docker/scripts/Dockerfile, how-to-guides/neptune-docker/scripts/requirements.txt, how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb, how-to-guides/organize-ml-experimentation/scripts/requirements.txt, how-to-guides/organize-ml-experimentation/scripts/run_examples.sh, how-to-guides/re-run-failed-training/notebooks/re_run_failed_training.ipynb, how-to-guides/re-run-failed-training/scripts/requirements.txt, how-to-guides/re-run-failed-training/scripts/run_examples.sh, integrations-and-supported-tools/altair/notebooks/Neptune_Altair_Support.ipynb, integrations-and-supported-tools/altair/scripts/requirements.txt, integrations-and-supported-tools/altair/scripts/run_examples.sh, integrations-and-supported-tools/bokeh/notebooks/Neptune_Bokeh_Support.ipynb, integrations-and-supported-tools/bokeh/scripts/requirements.txt, integrations-and-supported-tools/bokeh/scripts/run_examples.sh
* Unpinned dependencies
* Added `-U` and removed `-q` flags from pip install
* Added `-e` flag to `run_examples.sh`
__Note:__ 
* Tests on python3.11 are expected to fail because of library version incompatibilities
* Altair tests failing because of https://github.com/altair-viz/altair/issues/2705
* DDP tests are expected to fail. Will be excluded from PR tests in #169 
---
---
---
- OS:
=> Fix pip install - I

integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py
__Any expected test failures?__ Fastai v2 doesn't export the learner in MacOS but it runs normally on linux.
---
---
---
- OS: MacOS ventura
- Python version: 3.8.13
- Neptune version: 0.16.15
=> add pickling learner object example

integrations-and-supported-tools/altair/notebooks/Neptune_Altair_Support.ipynb, integrations-and-supported-tools/altair/scripts/requirements.txt
Reverts workaround applied for Altair in #183 as the issue has been fixed from Altair's end (https://github.com/altair-viz/altair/pull/2771)
---
---
---
- Python version: 3.7, 3.8,3.9, 3.10, 3.11
- Neptune version: 0.16.16
- Affected libraries with version: altair==4.2.1
=> Reverting altair workaround

integrations-and-supported-tools/pytorch-lightning/notebooks/Neptune_PyTorch_Lightning.ipynb
Added instructions for colab users to avoid `ContextualVersionConflict` error.
Tests might fail on python 3.11
---
---
---
- OS: 
=> Adding instructions for colab users

how-to-guides/data-versioning/notebooks/Compare_model_training_runs_on_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Organize_and_share_dataset_versions.ipynb, how-to-guides/data-versioning/notebooks/Version_datasets_in_model_training_runs.ipynb, how-to-guides/data-versioning/scripts/Compare_model_training_runs_on_dataset_versions.py, how-to-guides/data-versioning/scripts/Organize_and_share_dataset_versions.py, how-to-guides/data-versioning/scripts/Version_datasets_in_model_training_runs.py, how-to-guides/data-versioning/scripts/requirements.txt
* Downloading data during runtime
* Handling path resolution for all execution modes (and taking into account [neptune issue with tracking windows absolute paths](https://docs.neptune.ai/logging/artifacts/#passing-an-absolute-windows-file-path))
All failures are intentional `AssertionError`s
---
---
---
=> Fix for Compare_model_training_runs_on_dataset_versions

integrations-and-supported-tools/sacred/notebooks/Neptune_Sacred.ipynb
Setting `num_workers=0`
Tests will fail on python 3.11
---
---
---
- OS: Windows 11
- Neptune version: 0.16.17
=> Fixing sacred notebook test error

README.md, integrations-and-supported-tools/kedro/scripts/kedro-neptune-advanced/src/kedro_neptune_advanced/nodes.py, integrations-and-supported-tools/kedro/scripts/kedro-neptune-quickstart/src/kedro_neptune_quickstart/nodes.py, integrations-and-supported-tools/kedro/scripts/requirements.txt
Updated kedro example for neptune>=1.0.0
__Related to:__ `update examples`
Tests will fail on python 3.11
---
---
---
- Neptune version: 1.0.2
- Affected libraries with version: kedro-neptune==0.1.5
=> Updated kedro example for v1+

.github/workflows/test-notebooks.yml, integrations-and-supported-tools/optuna/notebooks/Neptune_Optuna_integration.ipynb, integrations-and-supported-tools/optuna/scripts/requirements.txt, integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/prophet/scripts/requirements.txt
* Updated optuna and prophet installation
* Fixed notebook test yaml for pytorch
Prophet tests will fail on Windows for py3.10 and py3.11 due to existing issue with plotly and matpotlib support
---
---
---
- OS:
=> Updated optuna, prophet installation; Fixed workflow yaml

integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/prophet/scripts/Neptune_prophet.py, integrations-and-supported-tools/prophet/scripts/requirements.txt, integrations-and-supported-tools/prophet/scripts/run_examples.sh
Added constraints to matplotlib and pandas versions
On Windows, tests will fail on python 3.10+ due to matplotlib<3.5 installation 
---
---
---
- Neptune version: 1.3.0
- Affected libraries with version: matplotlib<3.5, prophet==1.1.4, neptune-prophet==1.0.0, pandas<2.0
=> matplotlib prophet workaround

integrations-and-supported-tools/evidently/notebooks/Neptune_Evidently.ipynb, integrations-and-supported-tools/evidently/scripts/Neptune_Evidently_reports.py
scikit-learn>=1.3.0 expects `as_frame` to be boolean and "auto" is not longer accepted
---
---
---
- OS: Widows11
- Neptune version: 1.5.0
- Affected libraries with version: scikit-learn==1.3.0
=> Setting `as_frame=True`

integrations-and-supported-tools/colab/Neptune_Colab.ipynb
The "open in colab" link, which was also used in a blog post, is wrong and leads to a 404.
__Related to:__ https://app.clickup.com/t/8692nv0z9
---
---
---
- OS:
=> fix: link to open notebook in colab

integrations-and-supported-tools/matplotlib/notebooks/Neptune_Matplotlib_Support.ipynb, integrations-and-supported-tools/matplotlib/scripts/requirements.txt, integrations-and-supported-tools/matplotlib/scripts/run_examples.sh, integrations-and-supported-tools/prophet/notebooks/Neptune_prophet.ipynb, integrations-and-supported-tools/prophet/scripts/requirements.txt, integrations-and-supported-tools/prophet/scripts/run_examples.sh, use-cases/time-series-forecasting/walmart-sales/requirements.txt, use-cases/time-series-forecasting/walmart-sales/scripts/run_examples.sh
Unpinning matplotlib and pandas after plotly bugfix [#4372](https://github.com/plotly/plotly.py/pull/4372)
---
---
---
- Neptune version: 1.8.2
- Affected libraries with version: matplotlib==3.8.0, pandas==1.5.3, plotly==5.18.0
=> Unpinning matplotlib and pandas

integrations-and-supported-tools/lightgbm/notebooks/Neptune_LightGBM.ipynb, integrations-and-supported-tools/lightgbm/scripts/requirements.txt
Pinned scipy to <1.12 to prevent `ImportError`
---
---
---
- OS:
- Affected libraries with version: scipy>=1.12
=> Pinned scipy to <1.12

use-cases/nlp/classification/keras/code/keras_nb.ipynb, use-cases/nlp/classification/keras/code/keras_script.py
Added `wait=True` to `upload()` and `track_files()`
---
---
---
- OS:
=> Added `wait` to upload/track_files

integrations-and-supported-tools/detectron2/scripts/run_examples.sh
Added additional installation prerequisites
---
---
---
- OS:
=> Hopefully fixing detectron2 installation issue on macos for python>=3.11

how-to-guides/hello-neptune/notebooks/hello_neptune.ipynb, how-to-guides/hello-neptune/scripts/hello_neptune.py, how-to-guides/monitor-ml-runs/notebooks/Monitor_ML_runs_live.ipynb, how-to-guides/monitor-ml-runs/scripts/Monitor_ML_runs_live.py, integrations-and-supported-tools/airflow/scripts/Neptune_Airflow.py, integrations-and-supported-tools/detectron2/notebooks/Neptune_detectron2.ipynb, integrations-and-supported-tools/detectron2/scripts/Neptune_detectron2.py, integrations-and-supported-tools/fastai/notebooks/Neptune_fastai.ipynb, integrations-and-supported-tools/fastai/scripts/Neptune_fastai_more_options.py, integrations-and-supported-tools/keras/notebooks/Neptune_Keras.ipynb, integrations-and-supported-tools/keras/scripts/Neptune_Keras.py, integrations-and-supported-tools/keras/scripts/Neptune_Keras_more_options.py, integrations-and-supported-tools/mosaicml-composer/notebooks/Neptune_MosaicML_Composer.ipynb, integrations-and-supported-tools/mosaicml-composer/scripts/Neptune_MosaicML_Composer.py, integrations-and-supported-tools/skorch/notebooks/Neptune_Skorch.ipynb, integrations-and-supported-tools/skorch/scripts/Neptune_Skorch.py, integrations-and-supported-tools/skorch/scripts/Neptune_Skorch_more_options.py, integrations-and-supported-tools/tensorboard/notebooks/Neptune_Tensorflow_Tensorboard.ipynb, integrations-and-supported-tools/tensorboard/scripts/Neptune_Tensorflow_Tensorboard.py, integrations-and-supported-tools/tensorflow/notebooks/Neptune_Tensorflow.ipynb, integrations-and-supported-tools/tensorflow/scripts/Neptune_Tensorflow.py
Removed manual scale-down of images now that the client takes care of it
__Related to:__ Changes for image autoscaling
---
---
---
- Neptune version: 1.10.0
=> Removed manual image scaling

integrations-and-supported-tools/lightgbm/notebooks/Neptune_LightGBM.ipynb, integrations-and-supported-tools/lightgbm/scripts/requirements.txt, integrations-and-supported-tools/lightgbm/scripts/run_examples.sh
Constraining matplotlib to <3.9 as unmaintained dependency scikitplot now uses removed attributes
---
---
---
- Neptune version: 1.10.4 
- Affected libraries with version: matplotlib 3.9.0
=> COnstraining matplotlib to <3.9

.github/workflows/adhoc-test.yml, .github/workflows/pull-request.yml, .github/workflows/test-notebooks.yml, .github/workflows/test-scripts.yml, integrations-and-supported-tools/xgboost/scripts/Neptune_XGBoost_sklearn_api.py, integrations-and-supported-tools/xgboost/scripts/run_examples.sh
Fixed example to support xgboost>=2.0
---
---
---
- Neptune version:  1.10.4
- Affected libraries with version: neptune-xgboost==1.1.1
=> fix: Updated XGBoost example to support XGBoost>=2.0

how-to-guides/organize-ml-experimentation/notebooks/Organize_ML_runs.ipynb
Update the notebook section which mentions an older version of the run method to add tags to a run.
---
---
---
- OS: Windows 11
- Python version: 3.10.14
- Neptune version: 1.10.4
=> chore: Update notebook text to match the updated method for adding new tags to runs

how-to-guides/neptune-hpo/notebooks/Neptune_hpo.ipynb
The notebook does not render due to an error is in the JSON of the notebook. This fix removes the comma causing the issue and the notebook now renders correctly. 
---
---
---
- OS: Windows 10
- Python version: 3.10
- Neptune version: 1.10.4
=> fix: remove error from notebook JSON rendering

integrations-and-supported-tools/plotting-libraries/notebooks/Neptune_Plotting_Support.ipynb, integrations-and-supported-tools/plotting-libraries/scripts/Neptune_Plotting_Support.py
Added `include_plotlyjs="cdn" to interactive matplolib and plotly uploads
__Related to:__ NA
---
---
---
- Neptune version: 1.13.0
=> Fetching plotlyjs from cdn
